[package]
name = "ruizukun-dev/janitor"
version = "1.14.1"
license = "Apache2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = [
	"docs", ".moonwave", "test",
	"Janitor.rbxm", "Janitor.rbxmx", "BuildJanitor.lua",
	"changelog.md", "README.md", ".styluaignore", ".gitignore",
	"foreman.toml", "Luau.toml", "moonwave.toml", "rotriever.toml", "selene.toml", "stylua.toml", "testez-companion.toml", "testez.toml"
]

[dependencies]